export type Lang = "uz" | "en";

export type Shot = { src: string; device: "desktop" | "mobile" };

export type Project = {
  slug: string;
  title: string;
  tagline: { uz: string; en: string };
  description: { uz: string; en: string };
  highlights: { uz: string[]; en: string[] };
  stack: string[];
  live?: string;
  github?: string;
  images?: Shot[];
  badge?: { uz: string; en: string };
  selfHosted?: boolean;
  demo?: {
    label: { uz: string; en: string };
    entries: { role: string; email: string; password: string }[];
  };
  year: string;
  category: { uz: string; en: string };
};

export const projects: Project[] = [
  {
    slug: "manajoy",
    title: "ManaJoy",
    images: [
      { src: "/shots/manajoy-desktop-1.jpg", device: "desktop" },
      { src: "/shots/manajoy-desktop-2.jpg", device: "desktop" },
      { src: "/shots/manajoy-mobile-1.jpg", device: "mobile" },
      { src: "/shots/manajoy-mobile-2.jpg", device: "mobile" },
      { src: "/shots/manajoy-mobile-3.jpg", device: "mobile" },
      { src: "/shots/manajoy-mobile-4.jpg", device: "mobile" },
    ],
    tagline: {
      uz: "Onlayn marketplace — chegirmalar, do'konlar va xizmatlar",
      en: "Online marketplace — discounts, stores & services",
    },
    badge: { uz: "Ish joyi · Jamoa", en: "At work · Team" },
    description: {
      uz: "O'zbekiston bo'ylab ishlaydigan real onlayn marketplace. Mahsulotlar, yaqin do'konlar va xizmatlar (gaming zonalar, salonlar, sartaroshxonalar, sport, restoranlar — stol bron qilish bilan), loyalty kartalari va ball tizimi, sotuvchi bo'lish oqimi. Mijozlar sayti va ichki admin paneli ish joyida, jamoada, frontend yo'nalishida ishlab chiqiladi.",
      en: "A real, in-production online marketplace serving all of Uzbekistan — products, nearby stores and services (gaming venues, salons, barbershops, sports, restaurants with table reservations), loyalty cards and a points system, and seller onboarding. The customer-facing site and internal admin panel are developed with a team at work, in a frontend role.",
    },
    highlights: {
      uz: [
        "Mahsulot, do'kon va xizmatlar katalogi — qidiruv va filtrlash",
        "MapLibre GL bilan \"yaqin do'konlar\" xaritasi va geolokatsiya",
        "Loyalty — ballar, chegirma kartalari va aksiyalar",
        "Buyurtma kuzatuvi va xizmat/restoran bron qilish oqimi",
        "Ichki admin panel: mahsulot, do'kon, buyurtma boshqaruvi va statistika",
      ],
      en: [
        "Product, store and service catalog with search and filtering",
        "\"Nearby stores\" map and geolocation via MapLibre GL",
        "Loyalty — points, discount cards and promotions",
        "Order tracking and service/restaurant reservation flow",
        "Internal admin panel: product, store and order management with analytics",
      ],
    },
    stack: [
      "Next.js",
      "React",
      "TypeScript",
      "TailwindCSS",
      "shadcn/ui",
      "MapLibre GL",
      "TanStack Query",
      "React Hook Form",
      "Zod",
    ],
    live: "https://manajoy.uz",
    year: "2026",
    category: { uz: "Marketplace · Xizmatlar", en: "Marketplace · Services" },
  },
  {
    slug: "kelvin",
    title: "Kelvin",
    images: [
      { src: "/shots/kelvin-desktop.jpg", device: "desktop" },
      { src: "/shots/kelvin-desktop-2.jpg", device: "desktop" },
      { src: "/shots/kelvin-mobile.jpg", device: "mobile" },
    ],
    selfHosted: true,
    tagline: {
      uz: "Yoritish do'koni uchun e-commerce platforma",
      en: "Lighting-store e-commerce platform",
    },
    description: {
      uz: "Yoritish do'koni uchun boshdan-oyoq e-commerce platforma — vitrina, ombor, buyurtma, kassa (POS) va CRM. Yoritish sohasiga xos fasetli qidiruv: rang harorati (2700K–6500K), IP himoya darajasi, tsokol turi va lumen bo'yicha jonli filtr. Backend'da atomik zaxira (bir vaqtda sotib olishga qarshi), transactional outbox va buyurtma sagasi. Iliq-boutique dizaynda qayta ishlangan front.",
      en: "End-to-end commerce platform for a lighting store — storefront, inventory, orders, point-of-sale and CRM. Domain-specific faceted search: live filtering by colour temperature (2700K–6500K), IP rating, socket type and lumens. The backend uses an atomic conditional reservation (oversell-proof), a transactional outbox and an order saga. Front rebuilt in a warm-boutique design.",
    },
    highlights: {
      uz: [
        "Fasetli qidiruv (rang harorati, IP, tsokol, lumen) — Meilisearch",
        "Atomik zaxira: oversell'ga qarshi shartli UPDATE (poyga yo'q)",
        "Transactional outbox + BullMQ worker (ishonchli hodisalar)",
        "Buyurtma sagasi, yetkazish zonalari, Click/Payme to'lov oqimi",
        "Pul BigInt tiyinda (float emas), 9 migratsiya, POS · CRM · analitika",
      ],
      en: [
        "Faceted search (colour temperature, IP, socket, lumens) — Meilisearch",
        "Atomic reservation: oversell-proof conditional UPDATE (no race)",
        "Transactional outbox + BullMQ worker (reliable events)",
        "Order saga, delivery zones, Click/Payme payment flow",
        "Money as BigInt tiyin (never float), 9 migrations, POS · CRM · analytics",
      ],
    },
    stack: [
      "NestJS 11",
      "Prisma 6",
      "PostgreSQL",
      "Meilisearch",
      "Redis · BullMQ",
      "React 19",
      "Vite",
      "styled-components",
      "TanStack Query",
      "Docker",
    ],
    live: "https://kelvin.sarvarbek-sodiqov.uz",
    github: "https://github.com/Sarvarbek0704/kelvin",
    demo: {
      label: { uz: "Demo hisoblar", en: "Demo credentials" },
      entries: [
        { role: "Customer", email: "customer@kelvin.uz", password: "kelvin-dev-password" },
        { role: "Admin", email: "admin@kelvin.uz", password: "kelvin-dev-password" },
      ],
    },
    year: "2026",
    category: { uz: "E-commerce · Retail", en: "E-commerce · Retail" },
  },
  {
    slug: "birga",
    title: "Birga",
    images: [
      { src: "/shots/birga-desktop.jpg", device: "desktop" },
      { src: "/shots/birga-desktop-2.jpg", device: "desktop" },
      { src: "/shots/birga-mobile.jpg", device: "mobile" },
    ],
    selfHosted: true,
    tagline: {
      uz: "Real-time hamkorlikда matn muharriri",
      en: "Real-time collaborative editor",
    },
    description: {
      uz: "Bir hujjatда bir necha kishi bir vaqtда yozadigan real-time muharrir — jonli kursorlar, presence va offline'да ham konfliktсиз birlashadigan tahrirlar. Yadroда noldan yozilган sequence CRDT (`@birga/crdt`) va Rich rejim uchun Yjs. WebSocket sync server + Postgres op-log persistence. Rollar: owner/editor/viewer — viewer jonli read-only.",
      en: "A real-time editor where several people write in the same document at once — live cursors, presence, and edits that merge without conflicts even offline. Core is a from-scratch sequence CRDT (`@birga/crdt`) plus Yjs for Rich mode. WebSocket sync server + Postgres op-log persistence. Roles: owner/editor/viewer — viewers are live read-only.",
    },
    highlights: {
      uz: [
        "Noldan yozilган sequence CRDT (`@birga/crdt`) + Yjs Rich rejim",
        "Jonli kursorlar, presence, name-flag (real-time awareness)",
        "Offline-first: uzilса lokal saqlaydi, ulanганда konfliktсиз birlashadi",
        "Rol-asosli ruxsat — viewer jonli read-only (WS enforcement)",
        "WebSocket sync server + Postgres op-log + kompaktsiya",
      ],
      en: [
        "From-scratch sequence CRDT (`@birga/crdt`) + Yjs for Rich mode",
        "Live cursors, presence, name flags (real-time awareness)",
        "Offline-first: saves locally on drop, merges conflict-free on reconnect",
        "Role-based access — viewers are live read-only (WS enforcement)",
        "WebSocket sync server + Postgres op-log + compaction",
      ],
    },
    stack: [
      "Next.js 14",
      "TypeScript",
      "TipTap",
      "Yjs + custom CRDT",
      "WebSocket (ws)",
      "Node.js",
      "PostgreSQL",
      "TailwindCSS",
      "pnpm monorepo",
    ],
    live: "https://birga.sarvarbek-sodiqov.uz",
    github: "https://github.com/Sarvarbek0704/birga",
    badge: { uz: "Bir bosishда demo — Ada · Ben · Carol", en: "One-click demo — Ada · Ben · Carol" },
    year: "2026",
    category: { uz: "Real-time · Hamkorlik", en: "Real-time · Collaboration" },
  },
  {
    slug: "zehn",
    title: "Zehn",
    images: [
      { src: "/shots/zehn-desktop.jpg", device: "desktop" },
      { src: "/shots/zehn-desktop-2.jpg", device: "desktop" },
      { src: "/shots/zehn-mobile.jpg", device: "mobile" },
    ],
    selfHosted: true,
    tagline: {
      uz: "O'zbekcha hujjatlar ustidan iqtibosli AI-qidiruv",
      en: "Cited AI answers over Uzbek documents",
    },
    description: {
      uz: "O'zbek tilidagi hujjat korpusi (qonun, nizom, protsedura) ustidan savolga iqtibos bilan javob beradigan RAG-assistant. Har bir da'vo manba parchasiga bog'lanadi; korpus qo'llab-quvvatlamasa — \"Ma'lumot topilmadi\" deb rad etadi, to'qib chiqarmaydi. Yadroda: struktura-aware chunking, o'zbek morfologiyasiga moslashgan hybrid qidiruv (vektor + full-text, RRF birlashma) pgvector ustida, va SSE bilan oqib chiqadigan javob. Eng muhimi — eval harness: retrieval va javob sifati recall@k, MRR va faithfulness sonlar bilan o'lchanadi.",
      en: "A retrieval-grounded (RAG) assistant that answers questions over Uzbek document corpora (laws, regulations, procedures) with inline citations. Every claim links to its source passage; when the corpus doesn't support an answer it refuses (\"Ma'lumot topilmadi\") instead of hallucinating. Under the hood: structure-aware chunking, Uzbek-morphology-aware hybrid retrieval (vector + full-text, fused with RRF) on pgvector, and SSE-streamed answers. And critically — an evaluation harness that measures retrieval and answer quality with recall@k, MRR and faithfulness.",
    },
    highlights: {
      uz: [
        "Iqtibosli, grounded javob — har da'vo manba parchasiga bog'lanadi",
        "Korpusda yo'q bo'lsa \"Ma'lumot topilmadi\" — hallucination yo'q",
        "O'zbek morfologiyasiga moslashgan hybrid qidiruv (vektor + FTS, RRF)",
        "pgvector + struktura-aware chunking, SSE bilan stream javob",
        "Eval harness: recall@k · MRR · faithfulness — o'lchangan sifat",
        "Multi-tenant (org izolyatsiyasi) · email + OTP auth · pluggable LLM",
      ],
      en: [
        "Grounded, cited answers — every claim links to its source passage",
        "Refuses with \"Ma'lumot topilmadi\" when out of corpus — no hallucination",
        "Uzbek-morphology-aware hybrid retrieval (vector + FTS, RRF)",
        "pgvector + structure-aware chunking, SSE-streamed answers",
        "Eval harness: recall@k · MRR · faithfulness — quality with numbers",
        "Multi-tenant (org isolation) · email + OTP auth · pluggable LLM",
      ],
    },
    stack: [
      "TypeScript",
      "NestJS",
      "Next.js 14",
      "PostgreSQL + pgvector",
      "RAG · Hybrid retrieval (RRF)",
      "SSE streaming",
      "Pluggable LLM/embeddings",
      "BullMQ + Redis",
      "pnpm monorepo",
      "Docker",
    ],
    live: "https://zehn.sarvarbek-sodiqov.uz",
    github: "https://github.com/Sarvarbek0704/zehn",
    badge: { uz: "Demo: admin@navroz.demo · OTP ekranda", en: "Demo: admin@navroz.demo · OTP on screen" },
    year: "2026",
    category: { uz: "AI · RAG qidiruv", en: "AI · RAG retrieval" },
  },
  {
    slug: "manzara",
    title: "Manzara",
    images: [
      { src: "/shots/manzara-desktop.jpg", device: "desktop" },
      { src: "/shots/manzara-desktop-2.jpg", device: "desktop" },
      { src: "/shots/manzara-mobile.jpg", device: "mobile" },
    ],
    selfHosted: true,
    tagline: {
      uz: "O'zbekiston ko'chmas mulk bozori — ma'lumot ustidan tahlil",
      en: "Uzbekistan's property market, from raw data",
    },
    description: {
      uz: "Ko'chmas mulk e'lonlarini yig'ib, tozalab, bir kvartirani turli saytdagi takroridan bitta yozuvga birlashtirib (entity resolution), bozor tahliliga aylantiradigan data-engineering tizimi. Bu CRUD emas — qiymat butunlay pipeline'da: scraping, iflos ma'lumot normalizatsiyasi (uch valyuta, tartibsiz maydon, tuman nomlari), va precision/recall bilan o'lchangan dedup. Natija: tuman × xona bo'yicha median narx, uch oylik trend, va \"bu e'lon 12% qimmat\" deydigan valuation.",
      en: "A data-engineering system that scrapes property listings, cleans them, resolves the same flat listed on several sites into one record (entity resolution), and turns the mess into market analytics. Not a CRUD app — the value is entirely in the pipeline: scraping, dirty-data normalisation (three currencies, messy areas, district spellings), and deduplication measured with precision/recall. Output: median price by district × rooms, a 3-month trend, and a valuation that flags a listing as \"12% above market\".",
    },
    highlights: {
      uz: [
        "Entity resolution — bir kvartira ko'p saytda → bitta yozuv (blocking + skorlash)",
        "Dedup precision 98.5% / recall 92.9% — o'lchangan, taxmin emas",
        "Iflos ma'lumot normalizatsiyasi: 3 valyuta, maydon, kanonik tuman",
        "Tuman × xona median/p25/p75 narx + haftalik trend (time-series)",
        "Valuation — e'lonni bozor medianidan % yuqori/past baholaydi",
        "Immutable raw storage + idempotent pipeline · email + OTP auth",
      ],
      en: [
        "Entity resolution — the same flat across sites → one record (blocking + scoring)",
        "Dedup precision 98.5% / recall 92.9% — measured, not guessed",
        "Dirty-data normalisation: three currencies, areas, canonical districts",
        "Median/p25/p75 by district × rooms + weekly trend (time-series)",
        "Valuation — flags a listing as % above/below the district median",
        "Immutable raw storage + idempotent pipeline · email + OTP auth",
      ],
    },
    stack: [
      "TypeScript",
      "NestJS",
      "Next.js",
      "PostgreSQL + pg_trgm",
      "Playwright",
      "Entity resolution / dedup",
      "BullMQ + Redis",
      "Recharts",
      "pnpm monorepo",
      "Docker",
    ],
    live: "https://manzara.sarvarbek-sodiqov.uz",
    github: "https://github.com/Sarvarbek0704/manzara",
    badge: { uz: "Demo: istalgan email · OTP ekranda", en: "Demo: any email · OTP on screen" },
    year: "2026",
    category: { uz: "Data muhandisligi · Analitika", en: "Data engineering · Analytics" },
  },
  {
    slug: "multilevel-wisar",
    title: "Multilevel",
    images: [
      { src: "/shots/multilevel-desktop.jpg", device: "desktop" },
      { src: "/shots/multilevel-desktop-2.jpg", device: "desktop" },
      { src: "/shots/multilevel-mobile.jpg", device: "mobile" },
    ],
    tagline: {
      uz: "CEFR (UzBMB Multilevel) imtihoniga AI bilan tayyorgarlik",
      en: "CEFR (UzBMB Multilevel) exam prep with AI grading",
    },
    description: {
      uz: "O'zbekiston uchun bepul CEFR/Multilevel imtihon-tayyorlash platformasi. Kurslar, to'liq mock imtihonlar, spaced-repetition bilan so'z yodlash, shaxsiy o'quv reja — va eng muhimi, Writing/Speaking uchun AI baholash: yozma yoki og'zaki javobni yuborasiz, tizim CEFR darajasi (A1–C2), band ballari va o'zbek tilida batafsil izoh qaytaradi. Telegram bot bilan integratsiya va email OTP orqali kirish.",
      en: "A free CEFR/Multilevel exam-prep platform for Uzbekistan. Courses, full mock exams, spaced-repetition vocabulary, personal study plans — and, crucially, AI grading for Writing/Speaking: submit a written or spoken response and get a CEFR level (A1–C2), band scores, and detailed feedback in Uzbek. Telegram bot integration and email-OTP login.",
    },
    highlights: {
      uz: [
        "AI baholash (Gemini) — Writing/Speaking uchun CEFR daraja + band + izoh",
        "To'liq mock imtihonlar (barcha bo'limlar) + avtomatik natija",
        "Spaced-repetition so'z yodlash (1300+ so'z, C1 gacha)",
        "Telegram bot integratsiyasi (webhook) + email OTP kirish",
        "Kurslar, shaxsiy o'quv reja, xatolar ustida ishlash (drills)",
        "NestJS + Next.js monorepo, provayder-almashinadigan AI",
      ],
      en: [
        "AI grading (Gemini) — CEFR level + band + feedback for Writing/Speaking",
        "Full mock exams (all sections) with automatic scoring",
        "Spaced-repetition vocabulary (1300+ words, up to C1)",
        "Telegram bot integration (webhook) + email-OTP login",
        "Courses, personal study plans, mistake drills",
        "NestJS + Next.js monorepo, provider-swappable AI",
      ],
    },
    stack: [
      "TypeScript",
      "NestJS",
      "Next.js",
      "PostgreSQL + Prisma",
      "Gemini AI (grading)",
      "Telegram Bot API",
      "JWT + email OTP",
      "TailwindCSS",
      "pnpm monorepo",
      "Docker",
    ],
    live: "https://multilevel.wisar.uz",
    github: "https://github.com/Sarvarbek0704/multilevel-wisar",
    badge: { uz: "Bepul · AI baholash", en: "Free · AI grading" },
    year: "2026",
    category: { uz: "EdTech · AI baholash", en: "EdTech · AI grading" },
  },
  {
    slug: "ziyo",
    title: "Ziyo",
    images: [
      { src: "/shots/ziyo-desktop-1.png", device: "desktop" },
      { src: "/shots/ziyo-desktop-2.png", device: "desktop" },
      { src: "/shots/ziyo-desktop-3.png", device: "desktop" },
      { src: "/shots/ziyo-desktop-4.png", device: "desktop" },
      { src: "/shots/ziyo-desktop-5.png", device: "desktop" },
      { src: "/shots/ziyo-mobile-1.png", device: "mobile" },
      { src: "/shots/ziyo-mobile-2.png", device: "mobile" },
      { src: "/shots/ziyo-mobile-3.png", device: "mobile" },
      { src: "/shots/ziyo-mobile-4.png", device: "mobile" },
      { src: "/shots/ziyo-mobile-5.png", device: "mobile" },
    ],
    selfHosted: true,
    tagline: {
      uz: "Multi-tenant ta'lim boshqaruv platformasi",
      en: "Multi-tenant Learning Management System",
    },
    description: {
      uz: "Ta'lim muassasalari uchun to'liq funksional LMS/SIS platforma. Har bir maktab o'z izolyatsiyalangan ma'lumotlariga ega (multi-tenant arxitektura). Xodimlar uchun 30+ sahifa: akademik boshqaruv, davomat, intizom, moliya, kommunikatsiya. Ota-onalar uchun alohida 12 sahifalik panel — farzandning baholari, davomati, to'lovlari.",
      en: "Full-featured Learning & Student Information System for educational institutions. Each school has its own isolated data (multi-tenant architecture). 30+ staff pages covering academics, attendance, discipline, finance, and communications. Dedicated 12-page guardian portal for grades, attendance, and payments.",
    },
    highlights: {
      uz: [
        "56 ta DB modeli, 28 ta funksional modul",
        "Granular RBAC tizimi (dinamik rollar va ruxsatlar)",
        "JWT (access + refresh) + brute-force himoya + audit log",
        "BLOCK_TEST uchun 189 ballik maxsus baholash tizimi",
        "Real-time davomat va to'lov bildirishnomalari",
      ],
      en: [
        "56 database models, 28 feature modules",
        "Granular RBAC with dynamic roles and permissions",
        "JWT (access + refresh) + brute-force protection + audit log",
        "Custom 189-point grading system for block tests",
        "Real-time attendance and payment notifications",
      ],
    },
    stack: [
      "NestJS 11",
      "Prisma 7",
      "PostgreSQL",
      "React 18",
      "TypeScript",
      "TailwindCSS",
      "shadcn/ui",
      "TanStack Query",
      "Framer Motion",
      "Vite",
    ],
    live: "https://ziyo.sarvarbek-sodiqov.uz",
    github: "https://github.com/Sarvarbek0704/ziyo",
    demo: {
      label: { uz: "Demo — maktab (tenant): mathacademy", en: "Demo — school (tenant): mathacademy" },
      entries: [
        { role: "Admin (staff login)", email: "demo", password: "Demo1234!" },
        { role: "Parent (guardian login)", email: "mathacademy-MA-DEMO", password: "Demo1234!" },
      ],
    },
    year: "2026",
    category: { uz: "Ta'lim · LMS", en: "Education · LMS" },
  },
  {
    slug: "nexus",
    title: "Nexus",
    images: [
      { src: "/shots/nexus-desktop-1.png", device: "desktop" },
      { src: "/shots/nexus-desktop-2.png", device: "desktop" },
      { src: "/shots/nexus-desktop-3.png", device: "desktop" },
      { src: "/shots/nexus-desktop-4.png", device: "desktop" },
      { src: "/shots/nexus-desktop-5.png", device: "desktop" },
      { src: "/shots/nexus-desktop-6.png", device: "desktop" },
      { src: "/shots/nexus-desktop-7.png", device: "desktop" },
    ],
    selfHosted: true,
    tagline: {
      uz: "Freelance va agentlik marketplace platformasi",
      en: "Freelance & agency marketplace",
    },
    description: {
      uz: "Upwork tipidagi to'liq funksional freelance marketplace. 4 ta rol — Klient, Freelanser, Agentlik egasi, Admin. Klientlar loyiha joylaydi, freelancerlar bid taklif qiladi, kelishuv asosida shartnoma tuziladi va milestone asosida escrow to'lov tizimi orqali ish bajariladi. Greedy debt-settlement algoritmi minimal tranzaksiya sonida hisob-kitobni yopadi.",
      en: "Upwork-style freelance marketplace with four roles — Client, Freelancer, Agency Owner, Admin. Clients post projects, freelancers submit bids, contracts are managed with milestone-based escrow payments. A greedy debt-settlement algorithm closes accounts with the minimum number of transactions.",
    },
    highlights: {
      uz: [
        "Milestone asosidagi escrow to'lov tizimi",
        "Greedy debt-settlement algoritmi",
        "JWT + Google OAuth + GitHub OAuth (Passport.js)",
        "To'liq nizo (dispute) hal qilish moduli",
        "Platforma komissiyasi va ichki messaging",
      ],
      en: [
        "Milestone-based escrow payment system",
        "Greedy debt-settlement algorithm",
        "JWT + Google OAuth + GitHub OAuth (Passport.js)",
        "Full dispute resolution module",
        "Platform commission and in-app messaging",
      ],
    },
    stack: [
      "NestJS 10",
      "TypeORM",
      "PostgreSQL",
      "Next.js 14",
      "TypeScript",
      "Redux Toolkit",
      "RTK Query",
      "TailwindCSS",
      "Recharts",
    ],
    live: "https://nexus.sarvarbek-sodiqov.uz",
    github: "https://github.com/Sarvarbek0704/nexus",
    demo: {
      label: { uz: "Demo hisoblar", en: "Demo credentials" },
      entries: [
        { role: "Client", email: "demo.client@nexus.dev", password: "Demo@1234" },
        { role: "Freelancer", email: "demo.freelancer@nexus.dev", password: "Demo@1234" },
        { role: "Agency owner", email: "demo.agency@nexus.dev", password: "Demo@1234" },
        { role: "Admin", email: "demo.admin@nexus.dev", password: "Demo@1234" },
      ],
    },
    year: "2026",
    category: { uz: "Marketplace · FinTech", en: "Marketplace · FinTech" },
  },
  {
    slug: "ustoz",
    title: "Ustoz",
    images: [
      { src: "/shots/ustoz-desktop.jpg", device: "desktop" },
      { src: "/shots/ustoz-desktop-2.jpg", device: "desktop" },
      { src: "/shots/ustoz-mobile.jpg", device: "mobile" },
    ],
    tagline: {
      uz: "Jonli dars — WebRTC orqali sinf, yozib olinadi va qayta ko'riladi",
      en: "Live teaching — a real-time class over WebRTC, recorded and rewatchable",
    },
    badge: { uz: "Jonli mahsulot · Mijozli", en: "Live product · Has a client" },
    selfHosted: true,
    description: {
      uz: "Real ustozlar uchun ishlab chiqilgan, sotiladigan mahsulot — to'lovchi mijozi ham bor. Ustoz guruhga jonli (real-time) dars o'tadi, dars video sifatida saqlanadi va o'quvchilar uni ro'yxatdan o'tgan holda qayta ko'radi. Avtomatik baholanadigan testlar, ustoz baholaydigan uy ishlari, davomat va ko'rish (watch-tracking) nazorati — bu darsni to'liq kursga aylantiradi. Interfeys o'zbek, rus va ingliz tillarida. Mustaqil qurilgan va o'z serverida joylashtirilgan.",
      en: "A real, sellable product built for real teachers — it already has a paying client. A teacher runs a live (real-time) class over WebRTC, the session is recorded to durable storage, and enrolled students rewatch it — with auto-graded quizzes, teacher-graded assignments, attendance and watch-tracking that turn a lesson into a full course. Interface in Uzbek, Russian and English. Built independently and self-hosted.",
    },
    highlights: {
      uz: [
        "LiveKit (WebRTC) bilan jonli guruh darslari, past kechikish",
        "Darslarni R2/S3 saqlashga yozib olish va enrollment orqali qayta ko'rish",
        "Avtomatik baholanadigan testlar va ustoz baholaydigan uy ishlari",
        "Davomat, ko'rish (watch-tracking) va nazorat/monitoring",
        "Uz / Ru / En interfeys, NextAuth autentifikatsiya",
      ],
      en: [
        "Live group classes over LiveKit (WebRTC), low latency",
        "Recording to R2/S3 storage, rewatch gated behind enrollment",
        "Auto-graded quizzes and teacher-graded assignments",
        "Attendance, watch-tracking and monitoring",
        "Uz / Ru / En interface, NextAuth authentication",
      ],
    },
    stack: [
      "Next.js 16",
      "LiveKit (WebRTC)",
      "Prisma",
      "PostgreSQL",
      "NextAuth",
      "Cloudflare R2 (S3)",
      "TypeScript",
      "TailwindCSS",
      "Zod",
    ],
    live: "https://ustoz.sarvarbek-sodiqov.uz",
    github: "https://github.com/Sarvarbek0704/ustoz",
    demo: {
      label: { uz: "Demo hisoblar", en: "Demo credentials" },
      entries: [
        { role: "Student", email: "demo.student@ustoz.uz", password: "Demo1234!" },
        { role: "Teacher", email: "demo.teacher@ustoz.uz", password: "Demo1234!" },
        { role: "Admin", email: "demo.admin@ustoz.uz", password: "Demo1234!" },
      ],
    },
    year: "2026",
    category: { uz: "Ta'lim · Jonli dars", en: "Education · Live teaching" },
  },
  {
    slug: "helix",
    title: "Helix",
    images: [
      { src: "/shots/helix-desktop.jpg", device: "desktop" },
      { src: "/shots/helix-desktop-2.jpg", device: "desktop" },
      { src: "/shots/helix-mobile.jpg", device: "mobile" },
    ],
    selfHosted: true,
    tagline: {
      uz: "Klinika va kasalxonalar uchun boshqaruv platformasi",
      en: "Healthcare management platform",
    },
    description: {
      uz: "Klinika va kasalxonalar uchun to'liq tibbiyot boshqaruv tizimi. 5 ta foydalanuvchi roli — Bemor, Shifokor, Hamshira, Lab texnik va Admin — har biri uchun mos dashboard. Bemorlar shifokorlardan qabul olishi, tibbiy yozuvlarni ko'rishi, retseptlarini va lab natijalarini kuzatishi mumkin. Shifokorlar haftalik jadval va qabul oqimini boshqaradi.",
      en: "Full-stack hospital and clinic management system serving five distinct roles — Patient, Doctor, Nurse, Lab Technician, Admin — each with a role-specific dashboard. Patients book appointments, view medical records, track prescriptions and lab results. Doctors manage schedules and the appointment flow.",
    },
    highlights: {
      uz: [
        "Klinik workflow: qabul → ko'rik → tibbiy yozuv → retsept → lab buyurtma → natija → hisob-faktura → sug'urta",
        "5 ta rol, 18 ta entity, role-based dashboardlar",
        "OTP email tasdiqlash, JWT (15 daq access + 7 kun refresh)",
        "Hayotiy ko'rsatkichlar tracking (BP, puls, harorat, BMI)",
        "Sug'urta plani va da'volar (claims) tizimi",
      ],
      en: [
        "Clinical workflow: appointment → consultation → record → prescription → lab order → results → billing → insurance",
        "5 roles, 18 entities, role-specific dashboards",
        "OTP email verification, JWT (15min access + 7d refresh)",
        "Vital signs tracking (BP, heart rate, temperature, BMI)",
        "Insurance plans and claims system",
      ],
    },
    stack: [
      "NestJS 10",
      "TypeORM",
      "PostgreSQL",
      "Next.js 14",
      "TypeScript",
      "RTK Query",
      "TailwindCSS",
      "Framer Motion",
    ],
    live: "https://helix.sarvarbek-sodiqov.uz",
    github: "https://github.com/Sarvarbek0704/helix",
    demo: {
      label: { uz: "Demo hisoblar", en: "Demo credentials" },
      entries: [
        { role: "Admin", email: "demo.admin@helix.uz", password: "Demo@12345" },
        { role: "Doctor", email: "demo.doctor@helix.uz", password: "Demo@12345" },
        { role: "Nurse", email: "demo.nurse@helix.uz", password: "Demo@12345" },
        { role: "LabTech", email: "demo.labtech@helix.uz", password: "Demo@12345" },
        { role: "Patient", email: "demo.patient@helix.uz", password: "Demo@12345" },
      ],
    },
    year: "2026",
    category: { uz: "Tibbiyot · HealthTech", en: "Healthcare · HealthTech" },
  },
  {
    slug: "wisar",
    title: "Wisar",
    images: [
      { src: "/shots/wisar-desktop.jpg", device: "desktop" },
      { src: "/shots/wisar-desktop-2.jpg", device: "desktop" },
      { src: "/shots/wisar-mobile.jpg", device: "mobile" },
    ],
    tagline: {
      uz: "Dasturlash va ingliz tili o'rganish platformasi",
      en: "Programming & English learning platform",
    },
    badge: { uz: "Jonli mahsulot · Yakka", en: "Live product · Solo" },
    selfHosted: true,
    description: {
      uz: "O'zbek tilidagi bepul ta'lim platformasi — noldan senior+ gacha to'liq full-stack dasturlash kursi, 706+ maqola va 41+ bo'lim, ingliz tili va IELTS moduli. Interaktiv mashqlar, SM-2 spaced repetition flashcardlari, kunlik planner va streak tizimi bilan bilimni amaliyotga bog'laydi. Mustaqil qurilgan, o'z serverida va o'z domenida joylashtirilgan.",
      en: "A free Uzbek-language learning platform — a full-stack programming course from zero to senior+, 706+ articles across 41+ sections, plus English and IELTS modules. It ties theory to practice with interactive exercises, SM-2 spaced-repetition flashcards, a daily planner and a streak system. Built independently, self-hosted on its own domain.",
    },
    highlights: {
      uz: [
        "706+ maqola, 41+ bo'lim — noldan senior+ gacha kurs",
        "Interaktiv mashqlar: kod yozish, quiz, bo'sh joyni to'ldirish",
        "SM-2 algoritmi asosidagi spaced repetition flashcard tizimi",
        "IELTS Coach — mock testlar va progress kuzatuvi",
        "Kunlik planner, streak va progress dashboard (haftalik hisobot, sertifikat)",
      ],
      en: [
        "706+ articles across 41+ sections — a zero-to-senior+ course",
        "Interactive exercises: coding challenges, quizzes, fill-in-the-blank",
        "SM-2 spaced-repetition flashcard system",
        "IELTS Coach — mock tests and progress tracking",
        "Daily planner, streaks and a progress dashboard (weekly reports, certificates)",
      ],
    },
    stack: [
      "Next.js",
      "React",
      "TypeScript",
      "TailwindCSS",
      "Redux Toolkit",
      "TanStack Query",
      "Framer Motion",
    ],
    live: "https://wisar.uz",
    year: "2026",
    category: { uz: "Ta'lim · EdTech", en: "Education · EdTech" },
  },
  {
    slug: "karvon",
    title: "Karvon",
    images: [
      { src: "/shots/karvon-desktop.jpg", device: "desktop" },
      { src: "/shots/karvon-desktop-2.jpg", device: "desktop" },
      { src: "/shots/karvon-mobile.jpg", device: "mobile" },
    ],
    selfHosted: true,
    tagline: {
      uz: "To'liq stack e-commerce platforma",
      en: "Full-stack e-commerce marketplace",
    },
    description: {
      uz: "O'zbekiston bozori uchun ishlab chiqilgan to'liq funksional e-commerce platforma. 4 ta rol — Admin, Sotuvchi, Xaridor, Kuryer — har biri uchun alohida dashboard. Socket.io orqali real-time chat. Payme, Click va Uzum to'lov tizimlari uchun to'liq simulyator (token asosidagi to'lov sahifalari, webhook endpointlar).",
      en: "Production-grade e-commerce platform built for the Uzbek market with four distinct roles — Admin, Seller, Buyer, Courier — each with its own dashboard. Real-time chat via Socket.io. Fully simulated Payme/Click/Uzum payment system with token-based payment pages and webhook endpoints.",
    },
    highlights: {
      uz: [
        "4 ta rol, 26 ta entity, to'liq RBAC",
        "Socket.io bilan real-time chat",
        "Payme / Click / Uzum simulyator to'lov tizimi",
        "Sharp orqali avtomatik rasm optimizatsiyasi",
        "Demo hisoblar uchun maxsus DemoGuard",
      ],
      en: [
        "4 roles, 26 entities, full RBAC",
        "Real-time chat with Socket.io",
        "Simulated Payme / Click / Uzum payment system",
        "Automatic image optimization via Sharp",
        "Custom DemoGuard for read-only demo accounts",
      ],
    },
    stack: [
      "NestJS 11",
      "TypeORM",
      "PostgreSQL",
      "Socket.io",
      "React 19",
      "TypeScript",
      "TailwindCSS 4",
      "RTK Query",
      "Framer Motion",
    ],
    live: "https://karvon.sarvarbek-sodiqov.uz",
    github: "https://github.com/Sarvarbek0704/karvon",
    demo: {
      label: { uz: "Demo hisoblar", en: "Demo credentials" },
      entries: [
        { role: "Admin", email: "demo.admin@karvon.uz", password: "Demo12345!" },
        { role: "Seller", email: "demo.seller@karvon.uz", password: "Demo12345!" },
        { role: "Buyer", email: "demo.user@karvon.uz", password: "Demo12345!" },
      ],
    },
    year: "2026",
    category: {
      uz: "E-commerce · Marketplace",
      en: "E-commerce · Marketplace",
    },
  },
  {
    slug: "trellis",
    title: "Trellis",
    images: [
      { src: "/shots/trellis-desktop.jpg", device: "desktop" },
      { src: "/shots/trellis-desktop-2.jpg", device: "desktop" },
      { src: "/shots/trellis-mobile.jpg", device: "mobile" },
    ],
    selfHosted: true,
    tagline: {
      uz: "Multi-tenant jamoa loyiha-boshqaruv platformasi",
      en: "Multi-tenant team project-management platform",
    },
    description: {
      uz: "Jira / Linear / ClickUp uslubidagi jamoa boshqaruv platformasi — tenant izolyatsiyasi haqiqatan testdan o'tkazilgan. Kanban, ro'yxat va kalendar ko'rinishlari; real-time hamkorlik (Socket.io); rolga asoslangan huquqlar; workspace taklifnomalari; vaqt hisobi; hisobotlar; API kalitlar va imzolangan webhook'lar — bitta deploymentда ko'plab jamoalar, har workspace ma'lumotlari izolyatsiyada. BullMQ bilan fon vazifalari. Interfeys uz/ru/en.",
      en: "A focused Jira / Linear / ClickUp alternative with tenant isolation that is actually tested. Kanban, list and calendar views; real-time collaboration (Socket.io); role-based access; workspace invitations; time tracking; reporting; API keys and signed webhooks — many teams on one deployment, each workspace's data isolated from the rest. Background jobs via BullMQ. Interface in Uzbek, Russian and English.",
    },
    highlights: {
      uz: [
        "Multi-tenant arxitektura — testlangan tenant izolyatsiyasi",
        "Kanban / ro'yxat / kalendar, real-time hamkorlik (Socket.io)",
        "Rolga asoslangan huquqlar va workspace taklifnomalari",
        "Vaqt hisobi, hisobotlar, API kalitlar va imzolangan webhook'lar",
        "BullMQ + Redis bilan fon vazifalari va navbatlar",
      ],
      en: [
        "Multi-tenant architecture with tested tenant isolation",
        "Kanban / list / calendar views, real-time collaboration (Socket.io)",
        "Role-based access and workspace invitations",
        "Time tracking, reporting, API keys and signed webhooks",
        "Background jobs and queues via BullMQ + Redis",
      ],
    },
    stack: [
      "NestJS 10",
      "TypeORM",
      "PostgreSQL",
      "BullMQ",
      "Redis",
      "Socket.io",
      "Next.js 14",
      "TypeScript",
      "TanStack Query",
      "TailwindCSS",
    ],
    live: "https://trellis.sarvarbek-sodiqov.uz",
    github: "https://github.com/Sarvarbek0704/trellis",
    demo: {
      label: { uz: "Demo hisoblar (workspace: Demo)", en: "Demo credentials (workspace: Demo)" },
      entries: [
        { role: "Owner", email: "admin@trellis.local", password: "Demo@1234" },
        { role: "Admin", email: "pm@trellis.local", password: "Demo@1234" },
        { role: "Member", email: "dev@trellis.local", password: "Demo@1234" },
      ],
    },
    year: "2026",
    category: { uz: "Productivity · SaaS", en: "Productivity · SaaS" },
  },
  {
    slug: "meridian",
    title: "Meridian",
    images: [
      { src: "/shots/meridian-desktop.jpg", device: "desktop" },
      { src: "/shots/meridian-desktop-2.jpg", device: "desktop" },
      { src: "/shots/meridian-mobile.jpg", device: "mobile" },
    ],
    selfHosted: true,
    tagline: {
      uz: "Sayohat rejalashtirish platformasi",
      en: "Travel planning platform",
    },
    description: {
      uz: "Wanderlog va TripIt tipidagi to'liq sayohat rejalashtirish platformasi. Foydalanuvchilar ko'p-kunlik sayohatlar tuzadi, kun-kun itinerary builder bilan reja chizadi, guruh xarajatlarini avtomatik bo'ladi va sayohat sherigi (buddy) topadi. 20 ta dunyoning eng mashhur destinatsiyalari katalogi va sharhlar tizimi.",
      en: "Wanderlog/TripIt-style travel planning platform. Users plan multi-day trips, build day-by-day itineraries, automatically split group expenses, and find travel buddies. Curated catalog of 20 world destinations with a full review system.",
    },
    highlights: {
      uz: [
        "Kun-kun itinerary builder (drag-and-drop)",
        "Guruh xarajatlarini avtomatik bo'lish (greedy algoritm)",
        "Travel buddy finder — mos sherik tavsiyalari",
        "20 ta destination katalog va sharhlar",
        "OTP email autentifikatsiya, real-time bildirishnomalar",
      ],
      en: [
        "Day-by-day drag-and-drop itinerary builder",
        "Automatic group expense splitting (greedy algorithm)",
        "Travel buddy finder with matched suggestions",
        "20-destination curated catalog with reviews",
        "OTP email authentication, real-time notifications",
      ],
    },
    stack: [
      "NestJS 10",
      "TypeORM",
      "PostgreSQL",
      "Next.js 14",
      "TypeScript",
      "RTK Query",
      "TailwindCSS",
      "Nodemailer",
      "Framer Motion",
    ],
    live: "https://meridian.sarvarbek-sodiqov.uz",
    github: "https://github.com/Sarvarbek0704/meridian",
    demo: {
      label: { uz: "Demo hisob", en: "Demo credentials" },
      entries: [
        { role: "User", email: "demo@meridian.app", password: "Demo@2024" },
      ],
    },
    year: "2026",
    category: { uz: "Sayohat · Lifestyle", en: "Travel · Lifestyle" },
  },
  {
    slug: "javon",
    title: "Javon",
    images: [
      { src: "/shots/javon-desktop.jpg", device: "desktop" },
      { src: "/shots/javon-desktop-2.jpg", device: "desktop" },
      { src: "/shots/javon-mobile.jpg", device: "mobile" },
    ],
    selfHosted: true,
    tagline: {
      uz: "Onlayn kutubxona boshqaruv tizimi",
      en: "Online library management system",
    },
    description: {
      uz: "Onlayn kutubxona platforma — foydalanuvchilar kitoblarni bron qiladi, oladi va qaytaradi. 3 ta rol: User, Admin, Super Admin. Telefon + parol autentifikatsiya, a'zolik (Membership) tariflari va to'lov tizimi, kitob qaytarish so'rovlari, navbat (waitlist) tizimi, sharhlar va reyting.",
      en: "Online library platform where users can book, borrow, and return books. Three roles — User, Admin, Super Admin. Phone + password authentication, membership plans with payments, return-request workflow, waitlist system, reviews and ratings.",
    },
    highlights: {
      uz: [
        "3 ta rol, granular admin huquqlari",
        "Telefon + parol autentifikatsiya, SMS OTP moduli",
        "A'zolik tariflari (ELITE, PRO, PREMIUM) va to'lovlar",
        "Kitob bron qilish, qaytarish, waitlist navbati",
        "Cron jobs — muddati o'tgan bronlar va deadline ogohlantirishlar",
      ],
      en: [
        "3 roles with granular admin permissions",
        "Phone + password authentication, SMS OTP module",
        "Membership tiers (ELITE, PRO, PREMIUM) with payments",
        "Book booking, returns, waitlist queue",
        "Cron jobs for overdue bookings and deadline alerts",
      ],
    },
    stack: [
      "NestJS",
      "Prisma 7",
      "PostgreSQL",
      "React 18",
      "TypeScript",
      "Redux Toolkit",
      "TanStack Query",
      "Radix UI",
      "TailwindCSS",
      "Recharts",
    ],
    live: "https://javon.sarvarbek-sodiqov.uz",
    github: "https://github.com/Sarvarbek0704/javon",
    demo: {
      label: { uz: "Demo hisob (Admin)", en: "Demo credentials (Admin)" },
      entries: [
        { role: "Admin", email: "+998901112233", password: "Library@2026" },
      ],
    },
    year: "2026",
    category: { uz: "Ta'lim · Boshqaruv", en: "Education · Management" },
  },
];

export const skills = {
  frontend: [
    "React",
    "Next.js",
    "TypeScript",
    "Redux Toolkit",
    "RTK Query",
    "TanStack Query",
    "Tailwind CSS",
    "SCSS",
    "styled-components",
    "Vite",
  ],
  backend: [
    "Node.js",
    "NestJS",
    "Express",
    "REST API",
    "GraphQL",
    "WebSocket / Socket.io",
    "JWT / OAuth",
    "Prisma",
    "TypeORM",
    "Sequelize",
  ],
  databases: ["PostgreSQL", "MongoDB", "MySQL", "Redis"],
  tools: [
    "Git",
    "Docker",
    "Nginx",
    "Linux (VPS)",
    "Let's Encrypt / SSL",
    "CI/CD",
    "PostgreSQL admin",
    "Swagger",
    "Figma",
  ],
};

export const t = {
  nav: {
    work: { uz: "Loyihalar", en: "Work" },
    about: { uz: "Men haqimda", en: "About" },
    skills: { uz: "Ko'nikmalar", en: "Skills" },
    contact: { uz: "Aloqa", en: "Contact" },
    resume: { uz: "Resume", en: "Resume" },
  },
  hero: {
    greeting: { uz: "Salom, men", en: "Hello, I'm" },
    role: { uz: "Full-Stack Web Developer", en: "Full-Stack Web Developer" },
    based: { uz: "Toshkent, Oʻzbekiston", en: "Tashkent, Uzbekistan" },
    intro: {
      uz: "Toshkentda yashovchi Full-Stack Web Developer. Hozirda ManaJoy'da frontend dasturchi. Ish tashqarisida — jonli ishlaydigan 10 ta to'liq stack loyiha, barchasi VPS serverda, o'z domenida, Docker, Nginx va PostgreSQL bilan, HTTPS orqali.",
      en: "Full-Stack Web Developer based in Tashkent. Currently a frontend developer at ManaJoy. Outside work — ten full-stack projects, all live and self-hosted on a VPS with Docker, Nginx and PostgreSQL over HTTPS.",
    },
    cta1: { uz: "Loyihalarimni ko'ring", en: "View my work" },
    cta2: { uz: "Bog'lanish", en: "Get in touch" },
    available: { uz: "Ish uchun ochiqman", en: "Open to work" },
  },
  work: {
    eyebrow: { uz: "01 — Loyihalar", en: "01 — Selected Work" },
    title: { uz: "Mening loyihalarim", en: "Featured projects" },
    subtitle: {
      uz: "O'nta to'liq stack loyiha — hammasi jonli. ManaJoy ish joyida jamoada ishlab chiqiladi; qolganlari mustaqil loyihalar bo'lib, VPS serverda (Docker, Nginx, PostgreSQL, HTTPS) joylashtirilgan. Demo hisoblar bilan sinab ko'rish mumkin.",
      en: "Ten full-stack projects, all live. ManaJoy is built with a team at work; the rest are independent projects, self-hosted on a VPS (Docker, Nginx, PostgreSQL, HTTPS). Try them with the demo credentials.",
    },
    viewLive: { uz: "Saytni ochish", en: "Open live site" },
    viewCode: { uz: "Kodni ko'rish", en: "Source code" },
    privateCode: { uz: "Kod yopiq", en: "Private code" },
    selfHosted: { uz: "O'z serverimda jonli", en: "Live · self-hosted" },
    highlights: { uz: "Asosiy xususiyatlar", en: "Key features" },
    stack: { uz: "Texnologiyalar", en: "Tech stack" },
    closeBtn: { uz: "Yopish", en: "Close" },
  },
  about: {
    eyebrow: { uz: "02 — Men haqimda", en: "02 — About" },
    title: { uz: "Qisqacha biografiya", en: "A brief bio" },
    p1: {
      uz: "Toshkentda yashovchi 19 yoshli Full-Stack Web Developer. Najot Ta'limda 8 oylik intensiv Full-Stack bootcamp yakunlangan; hozirda Toshkent Davlat Iqtisodiyot Universitetining Axborot xavfsizligi yo'nalishi 3-kurs sirtqi talabasi.",
      en: "A 19-year-old Full-Stack Web Developer based in Tashkent. Completed an 8-month intensive Full-Stack bootcamp at Najot Ta'lim; currently a part-time 3rd-year Information Security student at Tashkent State University of Economics.",
    },
    p2: {
      uz: "2026-yil may oyidan ManaJoy'da frontend dasturchi — O'zbekiston bo'ylab ishlaydigan marketplace va uning admin paneli ustida, jamoada va project manager rahbarligida. Real mahsulot, kod-review va jamoada ishlash muhiti.",
      en: "Frontend developer at ManaJoy since May 2026 — a nationwide marketplace and its admin panel, within a team led by a project manager. A real product, with code review and teamwork.",
    },
    p3: {
      uz: "Ish tashqarisida 10 ta to'liq stack loyiha jonli — tibbiyot, e-commerce, ta'lim, jonli dars, freelance marketplace, sayohat, jamoa boshqaruvi va kutubxona sohalarida. Har biri multi-tenant DB, RBAC, JWT, real-time va to'lov oqimlarini o'z ichiga oladi; barchasi VPS serverda Docker, Nginx va PostgreSQL bilan, HTTPS orqali joylashtirilgan. Ustoz — to'lovchi mijozi bor mahsulot.",
      en: "Ten full-stack projects live outside work — healthcare, e-commerce, education, live teaching, freelance marketplaces, travel, team collaboration and library management. Each covers multi-tenant DB schemas, RBAC, JWT, real-time features and payment flows; all self-hosted on a VPS with Docker, Nginx and PostgreSQL over HTTPS. Ustoz is a product with a paying client.",
    },
    facts: {
      uz: [
        { k: "Joylashuv", v: "Toshkent, O'zbekiston" },
        { k: "Hozirgi ish", v: "Frontend Dev · ManaJoy" },
        { k: "Loyihalar", v: "10 jonli · 8 self-hosted" },
        { k: "Deploy", v: "Docker · Nginx · VPS" },
        { k: "Ta'lim", v: "TDIU + Najot Ta'lim" },
        { k: "Mavjudligi", v: "Yangi imkoniyatlarga ochiq" },
      ],
      en: [
        { k: "Location", v: "Tashkent, Uzbekistan" },
        { k: "Current role", v: "Frontend Dev · ManaJoy" },
        { k: "Projects", v: "10 live · 8 self-hosted" },
        { k: "Deployment", v: "Docker · Nginx · VPS" },
        { k: "Education", v: "TSUE + Najot Ta'lim" },
        { k: "Availability", v: "Open to opportunities" },
      ],
    },
  },
  skills: {
    eyebrow: { uz: "03 — Ko'nikmalar", en: "03 — Skills" },
    title: { uz: "Texnologiyalar", en: "Tech stack" },
    subtitle: {
      uz: "Har kuni ishlatadigan vositalarim. Ko'pchiligini chuqur bilaman, ba'zilarini hozircha asosiy darajada.",
      en: "Tools I work with daily. I know most deeply, some at a working level.",
    },
    groups: {
      frontend: { uz: "Frontend", en: "Frontend" },
      backend: { uz: "Backend", en: "Backend" },
      databases: { uz: "Ma'lumotlar bazasi", en: "Databases" },
      tools: { uz: "DevOps va vositalar", en: "DevOps & Tools" },
    },
  },
  experience: {
    eyebrow: { uz: "04 — Tajriba", en: "04 — Experience" },
    title: { uz: "Ish va ta'lim", en: "Experience & Education" },
    workLabel: { uz: "Ish tajribasi", en: "Work experience" },
    eduLabel: { uz: "Ta'lim", en: "Education" },
    work: {
      uz: [
        {
          place: "ManaJoy",
          role: "Frontend dasturchi",
          period: "2026-may — hozir",
          note: "O'zbekiston bo'ylab ishlaydigan onlayn marketplace (chegirmalar, do'konlar, xizmatlar, loyalty). Mijozlar sayti va ichki admin paneli React, Next.js va TypeScript'da — mahsulot va do'kon kataloglari, MapLibre bilan xarita, buyurtma va loyalty oqimlari. Project manager rahbarligida, jamoada.",
        },
      ],
      en: [
        {
          place: "ManaJoy",
          role: "Frontend Developer",
          period: "May 2026 — Present",
          note: "Nationwide online marketplace (discounts, stores, services, loyalty). Customer-facing site and internal admin panel with React, Next.js and TypeScript — product and store catalogs, MapLibre maps, order and loyalty flows. Team environment led by a project manager.",
        },
      ],
    },
    education: {
      uz: [
        {
          place: "Toshkent Davlat Iqtisodiyot Universiteti",
          role: "Bakalavr — Axborot xavfsizligi",
          period: "2024 — hozir",
          note: "Raqamli iqtisodiyot va axborot texnologiyalari fakulteti. 3-kurs talabasi, sirtqi ta'lim shaklida.",
        },
        {
          place: "Najot Ta'lim",
          role: "Full-Stack Web Development bootcamp",
          period: "2025 — 2026",
          note: "8 oylik intensiv kurs: Node.js, React, TypeScript, PostgreSQL, MongoDB. Sertifikatlangan.",
        },
      ],
      en: [
        {
          place: "Tashkent State University of Economics",
          role: "Bachelor's — Information Security",
          period: "2024 — Present",
          note: "Faculty of Digital Economy & Information Technologies. 3rd-year student, part-time / extramural program.",
        },
        {
          place: "Najot Ta'lim",
          role: "Full-Stack Web Development Bootcamp",
          period: "2025 — 2026",
          note: "8-month intensive program covering Node.js, React, TypeScript, PostgreSQL, MongoDB. Certified.",
        },
      ],
    },
  },
  contact: {
    eyebrow: { uz: "05 — Aloqa", en: "05 — Get in touch" },
    title: { uz: "Keling, gaplashaylik", en: "Let's talk" },
    subtitle: {
      uz: "Yangi imkoniyatlar, jamoa loyihalari yoki biror takliflaringiz bo'lsa yozing.",
      en: "Open to new opportunities, team projects, or just a friendly hello. I usually reply within a day.",
    },
    email: { uz: "Email", en: "Email" },
    telegram: { uz: "Telegram", en: "Telegram" },
    phone: { uz: "Telefon", en: "Phone" },
    github: { uz: "GitHub", en: "GitHub" },
    linkedin: { uz: "LinkedIn", en: "LinkedIn" },
  },
  resume: {
    title: { uz: "Resume yuklab olish", en: "Download resume" },
    options: {
      uz: [
        {
          label: "CV (O'zbek tilida) — 2 sahifa",
          file: "/Sarvarbek-Sodiqov-CV-uz.pdf",
        },
        {
          label: "CV (Ingliz tilida) — 2 sahifa",
          file: "/Sarvarbek-Sodiqov-CV-en.pdf",
        },
        {
          label: "Resume (O'zbek tilida) — 1 sahifa",
          file: "/Sarvarbek-Sodiqov-Resume-uz.pdf",
        },
        {
          label: "Resume (Ingliz tilida) — 1 sahifa",
          file: "/Sarvarbek-Sodiqov-Resume-en.pdf",
        },
      ],
      en: [
        { label: "CV (Uzbek) — 2 pages", file: "/Sarvarbek-Sodiqov-CV-uz.pdf" },
        {
          label: "CV (English) — 2 pages",
          file: "/Sarvarbek-Sodiqov-CV-en.pdf",
        },
        {
          label: "Resume (Uzbek) — 1 page",
          file: "/Sarvarbek-Sodiqov-Resume-uz.pdf",
        },
        {
          label: "Resume (English) — 1 page",
          file: "/Sarvarbek-Sodiqov-Resume-en.pdf",
        },
      ],
    },
  },
  footer: {
    rights: {
      uz: "© 2026 Sarvarbek Sodiqov. Barcha huquqlar himoyalangan.",
      en: "© 2026 Sarvarbek Sodiqov. All rights reserved.",
    },
    built: {
      uz: "React, TypeScript va Tailwind yordamida qurilgan — o'z serverimda hosted",
      en: "Built with React, TypeScript, and Tailwind — self-hosted on my own server",
    },
  },
};
